### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by hosseinab** [kanekoshoyu/kucoin_arbitrage#1]
hello
Please explain how to Run this project

**Comment by kanekoshoyu** [comment]
@hosseinab it's still quite rudimentary I haven't added the execution part yet, but let me add a how-to-run tutorial into the README in coming days.

**Comment by hosseinab** [comment]
@kanekoshoyu thank you . i'm waiting

**Comment by kanekoshoyu** [comment]
I had some feedback from others and went through the code logics. I made the update on README on how to run, but the project is very experimental at the moment and lots of things to be done ahead.
